services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Depa\SuluGoogleReviewsBundle\:
        resource: '../../src/'
        exclude:
            - '../../src/Entity/'
            - '../../src/DependencyInjection/'
            - '../../src/Translation/'
            - '../../src/DepaSuluGoogleReviewsBundle.php'

    Depa\SuluGoogleReviewsBundle\Admin\GoogleReviewsAdmin:
        tags:
            - { name: sulu.admin }
            - { name: sulu.context, context: admin }

    Depa\SuluGoogleReviewsBundle\Controller\Admin\GoogleReviewController:
        public: true
        tags:
            - { name: sulu.context, context: admin }
            - { name: controller.service_arguments }

    Depa\SuluGoogleReviewsBundle\Command\FetchGoogleReviewsCommand:
        # $apiKey/$placeId werden in der Extension aus der Bundle-Config gesetzt.
        tags:
            - { name: console.command }
